[project]
name = "clu-data-cleaning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "openai>=1.99.9",
    "pandas>=2.3.1",
]
